In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-11-27 13:11:41.153002: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[429, 431, 4248, 6097],
 [429, 431, 4248, 7244],
 [429, 4338, 4248, 9495],
 [1822, 2992, 4466, 4789, 1141],
 [1822, 2992, 4466, 4789, 5325],
 [5439, 429, 7559, 4248, 6621],
 [3135, 6395, 802, 4789]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  429  431 4248 6097]
 [   0    0    0    0  429  431 4248 7244]
 [   0    0    0    0  429 4338 4248 9495]
 [   0    0    0 1822 2992 4466 4789 1141]
 [   0    0    0 1822 2992 4466 4789 5325]
 [   0    0    0 5439  429 7559 4248 6621]
 [   0    0    0    0 3135 6395  802 4789]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/pythonpractical/mlenv/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-11-27 13:12:00.471034: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[[ 0.02747734, -0.03066806,  0.01603467,  0.01394154,
         -0.00794165,  0.02768717,  0.01253009,  0.04682989,
          0.01734861,  0.03620169],
        [ 0.02747734, -0.03066806,  0.01603467,  0.01394154,
         -0.00794165,  0.02768717,  0.01253009,  0.04682989,
          0.01734861,  0.03620169],
        [ 0.02747734, -0.03066806,  0.01603467,  0.01394154,
         -0.00794165,  0.02768717,  0.01253009,  0.04682989,
          0.01734861,  0.03620169],
        [ 0.02747734, -0.03066806,  0.01603467,  0.01394154,
         -0.00794165,  0.02768717,  0.01253009,  0.04682989,
          0.01734861,  0.03620169],
        [-0.02379963,  0.03044847, -0.03417617, -0.04333477,
          0.03636135, -0.02792298,  0.00181037,  0.02754143,
          0.00425159, -0.02118632],
        [-0.03713455, -0.04505167, -0.03326266,  0.04657701,
         -0.01794524, -0.02532408, -0.01546536,  0.04863762,
         -0.0456149 , -0.04363432],
        [-0.00327724, -0.04391509, -0.03384572, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  429,  431, 4248, 6097], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>